Valid email ID
Description
Consider that email IDs are supposed to be for the following format:
username@website.extension.
Here, there are three conditions to keep in mind:
1. The username can only contain characters 0-9, a-z and A-Z.
2. The website name can contain only characters a-z
3. The extension can have 2 or 3 alphabets(a-z).

Given an email ID, you have to determine if it is valid or not.

Sample Input:
prerna@upgrad.com

Sample Output:
valid
USED REGULAR EXPRESSION regex

In [72]:
import pandas as pd
import re
pd.set_option('display.max_columns', 500)

def checkmail(email):
    #complete the function
    #the function should return the strings "invalid" or "valid" based on the email ID entered
    res = 'valid'
    result = re.match("^[0-9a-zA-Z]+@[a-z]+\\.[a-z]{2,3}$", email)
    if result == None:
        res = 'invalid'
    return res


email= "0009A@website.com"

print(checkmail(email))
#Test with the following
#fname@dom.org
#f00name@dom.or
#fn9ame@domD.org
#fna9me@dom.org
#fname@dom.org
#fname@dom.orgr
#_Afname@dom.org
#Afname@dom.org
#Afname@dom.org
#Afname@dom.org
#Afname@dom.or4

valid


In [84]:
#Flattening array. With flatten or ravel. Only for lists
import numpy as np

lvl2List = np.array([[1, 2, 4], [2, 4, 5], [1, 2, 3]]) 
  
# printing initial arrays 
print("initial array", str(lvl2List)) 
# Multiplying arrays 
result = lvl2List.ravel() 
# printing result 
print("New resulting array: ", result)

initial array [[1 2 4]
 [2 4 5]
 [1 2 3]]
New resulting array:  [1 2 4 2 4 5 1 2 3]


In [104]:
import pandas as pd
from collections.abc import Iterable

#def isInstaceOfList(theElement):
#    if isinstance(theElement, list):
#        return True
#    return False
    
def isItemIterable(theElement):
    if isinstance(theElement, Iterable):
        # iterable
        return True
    else:
        # not iterable
        return False
        
lofL = [[1, 2, [45, 56]], [2, 4, 5], [1, 2, 3]]
#lofL = [[1, 2, 45], [2, 4, 5], [1, 2, 3]]

flt = [itm for sublst in lofL for itm in sublst]

print(flt)

print(isItemIterable(123))

[1, 2, [45, 56], 2, 4, 5, 1, 2, 3]
False


Squares

Description

Given a list of positive integers, you have to find numbers divisible by 3 and replace them with their squares. 

For example, consider the list below:
Input: [1,2,3,4,5,6]

The output for the above list would be: [1,2,9,4,5,36]. Because 3 and 6 were divisible by 3, these numbers were replaced with their squares.


In [116]:
chkSquare = lambda x : x*x if x%3 == 0 else x 
lst = [1,2,3,4,5,6]
res = [chkSquare(itm) for itm in lst]
res

[1, 2, 9, 4, 5, 36]

Write a program that computes the value of n+nn+nnn+nnnn with a given digit as the value of n.
For example, if n=9 , then you have to find the value of 9+99+999+9999.

In [156]:
from functools import reduce
sed=int(input())
sum = sed
arr = [None] * 4
for i in range(4):
    arr[i] = sum
    sum = sum * 10 + sed
    #print(arr) 

#print('DONE')
print(arr)
ans = reduce(lambda x, y: x+y, arr)
print(ans)
    

5
[5, 55, 555, 5555]
6170


2D array

Description

Write Python code which takes 2 numbers x and y as input and generates a 2-dimensional numpy array where value in the i-th row and j-th column of the array should be (i+j)/2.

Note: i=0,1,...x-1 and j=0,1....,y-1

The input will have two lines with x and y respectively.
The output should be a 2D numpy array.


In [163]:
import numpy as np

rows = 3
cols = 5
arr = np.empty(shape=(rows, cols),dtype='object') 

for i in range(rows):
    for j in range(cols): 
        arr[i][j] = (i + j) /2 
    
print (arr)

[[0.0 0.5 1.0 1.5 2.0]
 [0.5 1.0 1.5 2.0 2.5]
 [1.0 1.5 2.0 2.5 3.0]]


In [165]:
x=int(input())
y=int(input())
from numpy import zeros
a = zeros([x,y])
for row in range(x):
    for col in range(y):
        a[row][col]= (row+col)/2
print(a)

3
4
[[0.  0.5 1.  1.5]
 [0.5 1.  1.5 2. ]
 [1.  1.5 2.  2.5]]


#### Hypothesis testing in Python
You can easily do hypothesis testing in Python by using stats from Scipy library.

##### 1-sample t-test: testing the value of a population mean

To test, if the population mean of data is likely to be equal to a given value

In [166]:
scipy.stats.ttest_1samp()

stats.ttest_1samp(data['column'], x)
#where x is the mean value you want to test

NameError: name 'scipy' is not defined

##### 2-sample t-test: testing for difference across populations

In [168]:
scipy.stats.ttest_ind()

stats.ttest_ind(column_1,column_2)

NameError: name 'scipy' is not defined

##### Paired tests: repeated measurements on the same individuals

In [169]:
stats.ttest_rel()  

stats.ttest_rel(column_1,column_2)

NameError: name 'stats' is not defined

## import pandas as pd
pd.options.display.float_format = '${:,.2f}'.format
df = pd.DataFrame([123.4567, 234.5678, 345.6789, 456.7890],
                  index=['foo','bar','baz','quux'],
                  columns=['cost'])
print(df)

In [2]:
plt.figure(figsize=[20,20])

"""
pd.options.display.float_format = '{:,.2f}'.format

top9 = pd.pivot_table(data=master_frame.loc[master_frame['funding_round_type_upper'].isin([FUNDING_TYPE])],\
                      index="country_code", values="raised_amount_usd", aggfunc = np.sum)

top9 = top9 .sort_values(by=['raised_amount_usd'], ascending=False)[:9]
print(top9)


d = master_frame.loc[master_frame['funding_round_type_upper'].isin([FUNDING_TYPE])]

sns.barplot(data=d, x="country_code", y="raised_amount_usd", estimator=np.sum)
"""

#WORKS
top9.plot.bar(figsize=[13,10])

#d = master_frame.loc[master_frame['funding_round_type_upper'].isin([FUNDING_TYPE])]
#dg = d.groupby(['country_code']).agg({'raised_amount_usd':sum}) #.plot.bar()
#dgs = dg.apply(lambda x: x.sort_values(ascending=False).head(9))
#dgs.plot.bar(figsize=[13,10])

plt.gca().yaxis.set_major_formatter(FuncFormatter(lambda x, _: '${:0,.0f}'.format(x)))

plt.show()

"""
df_agg = df.groupby(['job','source']).agg({'count':sum})
We group by the first level of the index:

In [63]: g = df_agg['count'].groupby('job', group_keys=False)
Then we want to sort ('order') each group and take the first three elements:

In [64]: res = g.apply(lambda x: x.sort_values(ascending=False).head(3))
    """

https://stackoverflow.com/questions/47984547/sort-a-2-index-pivot-table-values-within-group-index-based-on-values
https://stackoverflow.com/questions/45300428/sorting-pivot-table-multi-index/45300480#45300480
https://stackoverflow.com/questions/10595327/pandas-sort-pivot-table
https://www.geeksforgeeks.org/matplotlib-axis-axis-set_major_formatter-function-in-python/

SyntaxError: invalid syntax (<ipython-input-2-82328d1e59fc>, line 40)

In [3]:
#Basics of probability
#Expected total loss
import numpy as np
import pandas as pd

    
fileName = "Inferential Statistics - Student Loan.csv"
bank_loan = pd.read_csv(fileName)

bank_loan.columns

bank_loan['recovery'] = bank_loan['Recovery (%)'].\
                        apply(lambda x: x.replace("%",'')).astype(float).divide(100)
bank_loan['loss'] = (1 - bank_loan['recovery']).\
                    mul(bank_loan['Exposure at Default (in lakh Rs.)'])

mulCol = bank_loan['loss'].mul(bank_loan['Probability of Default'])

print(mulCol.sum())

493.39131440619997


There are two possible values of X, 3,500 and -100. The probability of Kriti’s net winnings being 3,500 is basically the probability of her winning the game, which, as we saw in a previous question, is 1/37. The probability of her net winnings being equal to -100 is basically the probability of her losing the game, which is 36/37. So, the expected value of X = P(X=-100)*(-100) + P(X=3500)*3500 = (36/37)*(-100)+(1/37)*(3500) = -2.70.